modLoader="javafml"
loaderVersion="[36,)"
license="LGPL V3"

[[mods]]
modId="berrybushesdonthurtvillagers"
version="1.0"
displayName="Berry Bushes Don't Hurt Villagers"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/berry-bushes-dont-hurt-villagers"
#logoFile="logo.png"
#credits="credits"
authors="StephenBarnes"
description='''
Prevent berry bushes from causing damage to villagers.'''

[[dependencies.berrybushesdonthurtvillagers]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.berrybushesdonthurtvillagers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
